-- Arquivo de apoio, caso você queira criar tabelas como as aqui criadas para a API funcionar.
-- Você precisa executar os comandos no banco de dados para criar as tabelas,
-- ter este arquivo aqui não significa que a tabela em seu BD estará como abaixo!

/*
comandos para mysql server
*/

create database learntot;
use learntot;

create table usuario (
id int primary key auto_increment,
nome varchar(45) not null,
email varchar(60) not null,
senha varchar(45) not null,
genfav varchar(45) not null
);

create table musica (
id int primary key auto_increment,
nome varchar(45) not null,
artista varchar(45) not null,
letra mediumtext not null,
genero varchar(45) not null,
idioma varchar(45) not null
)auto_increment = 100;

create table traducao(
id int primary key auto_increment,
fkmusica int unique not null,
letra_trad mediumtext not null,
idioma varchar(45) not null,
constraint fk_musica foreign key(fkmusica) references musica(id)
);

create table comentario(
id int primary key auto_increment,
texto tinytext not null,
avaliacao int not null,
fkusuario int not null,
fktraducao int not null,
constraint chk_avaliacao check (avaliacao in (1, 2, 3, 4, 5)),
constraint fk_traducao foreign key(fktraducao) references traducao(id),
constraint fk_usuario_comentario foreign key(fkusuario) references usuario(id)
)auto_increment = 100;

insert into usuario (nome, email, senha, genfav) 
values		('Ronaldo', 'ronaldo@gmail.com', 'senha1', 'Rock'),
			('Carlos', 'carlos@email.com', 'senha2', 'Pop'),
			('Julia', 'julia@gmail.com', 'senha3', 'Rock'),
			('Pedro', 'pedro@gmail.com', 'senha4', 'Funk'),
			('João', 'joao@email.com', 'senha5', 'Indie');
            
insert into musica (nome, artista, letra, genero, idioma) 
values		('Tom Sawyer', 'Rush', 'A modern-day warrior\nMean, mean stride\nToday\'s Tom Sawyer\nMean, mean pride\nThough his mind is not for rent\nDon\'t put him down as arrogant\nHis reserve, a quiet defense\nRiding out the day\'s events\nThe river\nWhat you say about his company\nIs what you say about society\nCatch the mist, catch the myth\nCatch the mystery, catch the drift\nThe world is, the world is\nLove and life are deep\nMaybe as his skies are wide\nToday\'s Tom Sawyer\nHe gets high on you\nAnd the space he invades\nHe gets by on you\nNo, his mind is not for rent\nTo any god or government\nAlways hopeful, yet discontent\nHe knows changes aren\'t permanent\nBut change is\nAnd what you say about his company\nIs what you say about society\nCatch the witness, catch the wit\nCatch the spirit, catch the spit\nThe world is, the world is\nLove and life are deep\nMaybe as his eyes are wide\nExit the warrior\nToday\'s Tom Sawyer\nHe gets high on you\nAnd the energy you trade\nHe gets right on to the friction of the day\n', 'Rock', 'Inglês'),
			('Lover, You Should’ve Come Over', 'Jeff Buckley', 'Looking out the door I see the rain\nFall upon the funeral mourners\nParading in a wake of sad relations\nAs their shoes fill up with water\nMaybe I\'m too young\nTo keep good love from going wrong\nBut tonight you\'re on my mind\nSo... you\'ll never know\nBroken down and hungry for your love\nWith no way to feed it\nWhere are you tonight?\nChild, ya know how much I need it\nToo young to hold on\nAnd too old to just break free and run\nSometimes a man gets carried away\nWhen he feels like should be having his fun\nMuch too blind to see the damage he\'s done\nSometimes a man must awake to find that\nReally he has no one\nSo I\'ll wait for you, love\nAnd I\'ll burn\nWill I ever see your sweet return?\nOh, will I ever learn?\nOh-oh, lover, you should\'ve come over\n\'Cause it\'s not too late\nLonely is the room, the bed is made\nThe open window lets the rain in\nBurning in the corner is the only one\nWho dreams he had you with him\nMy body turns and yearns\nFor a sleep that won\'t ever come\nIt\'s never over\nMy kingdom for a kiss upon her shoulder\nIt\'s never over\nAll my riches for her smiles\nWhen I\'ve slept so soft against her\nIt\'s never over\nAll my blood for the sweetness of her laughter\nIt\'s never over\nShe is the tear that hangs inside my soul forever\nOh, but maybe I\'m just too young\nTo keep good love from going wrong\nOh-oh-oh, lover\nYou should\'ve come over, yeah, yes\nYes, I feel too young to hold on\nAnd much too old to break free and run\nToo deaf, dumb and blind to see the damage I\'ve done\nSweet lover, you should\'ve come over\nOh, love, well I\'ve waited for you\nLover, lover, lover\nLover, love, love, love, love, love, love!\nLover, you should\'ve come over\n\'Cause it\'s not too late\n', 'Alternativo', 'Inglês'),
			('Wuthering Heights', 'Kate Bush', 'Out on the wily, windy moors\nWe\'d roll and fall in green\nYou had a temper like my jealousy\nToo hot, too greedy\nHow could you leave me\nWhen I needed to possess you?\nI hated you, I loved you too\nBad dreams in the night\nThey told me I was going to lose the fight\nLeave behind my Wuthering, Wuthering\nWuthering Heights\nHeathcliff, it\'s me, I\'m Cathy\nI\'ve come home, I\'m so cold\nLet me in your window\nHeathcliff, it\'s me I\'m Cathy\nI\'ve come home, I\'m so cold\nLet me in your window\nOoh, it gets dark, it gets lonely\nOn the other side from you\nI pine a lot, I find the lot\nFalls through without you\nI\'m coming back love, cruel Heathcliff\nMy one dream, my only master\nToo long I roam in the night\nI\'m coming back to his side to put it right\nI\'m coming home to wuthering, wuthering\nWuthering Heights\nHeathcliff, it\'s me, I\'m Cathy\nI\'ve come home, I\'m so cold\nLet me in your window\nHeathcliff, it\'s me, I\'m Cathy\nI\'ve come home, I\'m so cold\nLet me in your window\nOoh, let me have it\nLet me grab your soul away\nOoh, let me have it\nLet me grab your soul away\nYou know it\'s me, Cathy\nHeathcliff, it\'s me I\'m Cathy\nI\'ve come home, I\'m so cold\nLet me in your window\nHeathcliff, it\'s me, I\'m Cathy\nI\'ve come home, I\'m so cold\nLet me in your window\nHeathcliff, it\'s me, I\'m Cathy\nI\'ve come home, I\'m so cold', 'Pop', 'Inglês'),
			('Papaoutai', 'Stromae','Dites-moi d\'où il vient\nEnfin je saurai où je vais\nMaman dit que lorsqu\'on cherche bien\nOn finit toujours par trouver\nElle dit qu\'il n\'est jamais très loin\nQu\'il part très souvent travailler\nMaman dit "travailler, c\'est bien"\nBien mieux qu\'être mal accompagné\nPas vrai?\nOù est ton papa?\nDis-moi, où est ton papa?\nSans même devoir lui parler\nIl sait ce qui ne va pas\nAh, sacré papa\nDis-moi, où es-tu caché?\nÇa doit faire au moins mille fois que j\'ai\nCompté mes doigts\nHey\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, où t\'es où, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, où t\'es où, papaoutai?\nQuoi? Qu\'on y croie ou pas\nY aura bien un jour où on n\'y croira plus\nUn jour ou l\'autre, on sera tous papas\nEt d\'un jour à l\'autre, on aura disparu\nSerons-nous détestables?\nSerons-nous admirables?\nDes géniteurs ou des génies?\nDites-nous qui donne naissance aux irresponsables?\nAh, dites-nous qui?\nTiens, tout le monde sait comment on fait des bébés\nMais personne sait comment on fait des papas\nMonsieur je-sais-tout en aurait hérité, c\'est ça\nFaut l\'sucer d\'son pouce ou quoi?\nDites-nous où c\'est caché, ça doit\nFaire au moins mille fois qu\'on a\nBouffé nos doigts\nHey\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, où t\'es où, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, où t\'es où, papaoutai?\nOù est ton papa?\nDis-moi, où est ton papa?\nSans même devoir lui parler\nIl sait ce qui ne va pas\nAh, sacré papa\nDis-moi, où es-tu caché?\nÇa doit faire au moins mille fois que j\'ai\nCompté mes doigts\nOù est ton papa?\nDis-moi, où est ton papa?\nSans même devoir lui parler\nIl sait ce qui ne va pas\nAh, sacré papa\nDis-moi, où es-tu caché?\nÇa doit faire au moins mille fois que j\'ai\nCompté mes doigts\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, où t\'es où, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, papaoutai?\nOù t\'es, où t\'es où, papaoutai?', 'Pop', 'Francês'),
			('Since I´ve Been Loving You', 'Led Zeppelin','Working from seven to eleven every night\nIt really makes life a drag, I don\'t think that\'s right\nI\'ve really, been the best, the best of fools\nI did what I could, yeah\n\'Cause I love you, baby\nHow I love you, darling\nHow I love you, baby\nHow I love you, girl, little girl\nBaby, since I\'ve been loving you, yeah\nI\'m about to lose my worried mind, oh yeah\nEverybody trying to tell me\nThat you didn\'t mean me no good\nI\'ve been trying, Lord, let me tell you\nLet me tell you I really did the best I could\nI\'ve been working from seven to eleven every night\nI said it kinda makes my life a drag, drag, drag, drag,\nLord, that ain\'t right\nSince I\'ve been loving you\nI\'m about to lose my worried mind\nSaid I\'ve been crying, my tears they fell like rain\nDon\'t you hear, don\'t you hear them falling\nDo you remember, mama, when I knocked upon your door?\nI said you had the nerve to tell me\nyou didn\'t want me no more, yeah\nI open my front door,\nhear my back door slam\nYou must have one of them new fangled back door man\nI\'ve been working from seven, seven, seven,\nto eleven every night\nIt kinda makes my life a drag, drag, drag\nBaby, since I\'ve been loving you\nI\'m about to lose\nI\'m about lose to my worried mind\n','Rock', 'Inglês');
            
insert into traducao (fkmusica, letra_trad, idioma) 
values		(100, 'Um guerreiro dos dias modernos\nSignifica um grande passo\nO Tom Sawyer moderno\nSignifica orgulho\nEmbora sua mente não esteja à venda\nNão o diga arrogante\nSeu jeito reservado, uma defesa silenciosa\nLevando em frente os eventos do dia\nO rio\nO que você diz sobre sua companhia\nÉ o que você diz sobre sociedade\nPegue a névoa, pegue o mito\nPegue o mistério, pegue a traição\nO mundo é, o mundo é\nAmor e vida são profundos\nTalvez como seus céus são largos\nO Tom Sawyer moderno\nEle se liga em você\nE o espaço que ele invade\nComeça perto de você\nNão, sua mente não está à venda\nPara nenhum deus ou governo\nSempre esperançoso, ainda que descontente\nEle sabe que mudanças não são permanentes\nMas que mudar é\nE o que você diz sobre sua companhia\nÉ o que você diz sobre sociedade\nPegue a testemunha, pegue a sagacidade\nPegue o espírito, pegue o cuspe\nO mundo é, o mundo é\nAmor e vida são profundos\nTalvez como seus olhos são largos\nSaia o guerreiro\nO Tom Sawyer moderno\nEle se liga em você\nE a energia que você troca\nEle fica ligado na fricção do dia\n', 'Português'),
			(101, 'Olhando pela porta, eu vejo a chuva\nQue cai nos lutos fúnebres\nDesfilando em uma vigília de relações tristes\nEnquanto seus sapatos se enchem de água\nE talvez eu seja muito novo\nPara impedir que um bom amor dê errado\nMas esta noite você está em meus pensamentos\nEntão, nunca se sabe\nDespedaçado e faminto por seu amor\nSem nenhuma maneira de me alimentar\nOnde está você esta noite?\nQuerida, você sabe o quanto eu preciso\nSou jovem demais para esperar\nE velho demais para simplesmente me libertar e correr\nÀs vezes, o homem se deixa levar\nQuando sente que na verdade ele deveria estar se divertindo\nE é cego demais para ver o dano que causou\nÀs vezes, o homem deve acordar para descobrir que\nNa verdade, ele tem ninguém\nEntão eu vou esperar por você\n e vou queimar\nSerá que vou assistir ao seu doce retorno\nOh, será que um dia vou aprender?\nOh, amor, você deveria ter vindo para cá\nPorque não é tarde demais\nSolitário é o quarto em que a cama está feita\nA janela aberta deixa a chuva entrar\nQueimando no canto, está o único\nQue sonha que já teve você com ele\nMeu corpo vira e anseia\nPor um descanso que nunca virá\nNunca tem fim\nMeu reino por um beijo no ombro dela\nNunca tem fim\nTodas as minhas riquezas pelos seus sorriso\nQuando eu dormia tão gentilmente encostado nela\nNunca tem fim\nTodo o meu sangue pela doçura da risada dela\nNunca tem fim\nEla é a lágrima que está dentro de minha alma para sempre\nBem, talvez eu seja jovem demais\nPara impedir que um bom amor dê errado\nOh... amor\nVocê deveria ter vindo para cá\nSim, sim, me sinto jovem demais para esperar\nE velho demais para me libertar e correr\nSurdo demais, burro e cego para ver o dano que eu fiz\nDoce amor, você deveria ter vindo pra cá\nOh, amor, bem, estou esperando por você\nAmor, amor, amor\nAmor, amor, amor, amor, amor, amor\nAmor, amor, amor, você deveria ter vindo pra cá\nPorque não é tarde demais\n', 'Português'),
			(102, 'Lá fora nas campinas tempestuosas\nNós rolávamos e caíamos no gramado\nSeu temperamento era como o meu ciúme\nArdente demais, ávido demais\nComo você pôde me abandonar\nQuando eu precisei te possuir?\nEu te odiei, eu te amei também\nSonhos ruins durante a noite\nEles disseram-me que eu perderia a luta\nDeixo para trás meu morro, morro\nMorro dos ventos uivantes\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\nDeixe-me entrar por sua janela\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\nDeixe-me entrar por sua janela\nOh, fica escuro, fica solitário\nDo outro lado, longe de você\nEu definho tanto, eu noto que o destino\nFracassa sem você\nEstou voltando, amor, cruel Heathcliff\nMeu único sonho, meu único mestre\nPor muito tempo eu vago pela noite\nEstou voltando para o seu lado para consertar isso\nEstou voltando para o meu morro, morro\nMorro dos ventos uivantes\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\nDeixe-me entrar por sua janela\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\nDeixe-me entrar por sua janela\nOh, deixe-me ter\nDeixe-me levar sua alma embora\nOh, deixe-me ter\nDeixe-me levar sua alma embora\nVocê sabe que sou eu, Cathy\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\nDeixe-me entrar por sua janela\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\nDeixe-me entrar por sua janela\nHeathcliff, sou eu, Cathy\nVoltei para casa, estou com tanto frio\n', 'Português'),
			(103, 'Diga-me de onde ele vem\nE então eu saberei para onde estou indo\nMamãe diz que se você procura bem,\nSempre acabará encontrando\nEla diz que ele nunca está muito longe\nQue ele trabalha muito\nMamãe diz que trabalhar é bom,\nBem melhor que estar em má companhia\nNão é?\nOnde está o seu pai?\nDiga-me, onde está o seu pai?\nSem mesmo nos responder,\nEle sabe o que está errado\nAh, sagrado pai!\nDiga-me onde você tem se escondido!\nDevem ter sido pelo menos mil vezes que eu\nContei nos dedos\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você, onde está você?\nOnde, papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você, onde está você?\nOnde, papai, onde está você?\nSe acreditamos nisso ou não,\nUma hora não vamos mais\nMais cedo ou mais tarde seremos todos pais\nE de um dia para o outro, teremos desaparecido\nSeremos detestáveis?\nSeremos admiráveis?\nGenitores ou gênios?\nDigam-nos, quem dá à luz os irresponsáveis?\nAh, digam-nos quem\nTodo mundo sabe come fazer bebês\nMas ninguém sabe como fazer pais\nSenhor, "eu sei tudo", deve tê-lo herdado, é isso\nEstá chupando o dedo ou o quê?\nDigam-nos onde está escondido\nDevem ter sido ao menos mil vezes que nós\nContamos nossos dedos\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você, onde está você?\nOnde, papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você, onde está você?\nOnde, papai, onde está você?\nOnde está o seu papai?\nDiga-me, onde está o seu papai?\nSem mesmo falar com ele,\nEle sabe o que está errado\nAh, sagrado papai!\nDiga-me onde você se escondeu!\nDevem ter sido ao menos mil vezes que eu\nContei meus dedos\nOnde está o seu papai?\nDiga-me, onde está o seu papai?\nSem mesmo nos responder,\nEle sabe o que está errado\nAh, sagrado papai!\nDiga-me onde você se escondeu!\nDevem ter sido ao menos mil vezes que eu\nContei meus dedos\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você, onde está você?\nOnde, papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você? Papai, onde está você?\nOnde está você, onde está você?\nOnde, papai, onde está você?\n', 'Português'),
			(104, 'Trabalhando das sete às onze, todas as noites,\nIsso faz da vida um saco, acho que isto não está certo.\nEu realmente, tenho bancado o perfeito idiota,\neu fiz o que pude.\nPois eu te amo, baby,\nComo eu te amo, querida,\nComo eu te amo, baby,\nComo eu te amo, garota, garotinha.\nMas baby, desde que andei amando você,\nestou a ponto de perder minha mente angustiada, oh, yeah.\nTodo mundo tenta me dizer\nque você não quis me fazer nenhum bem.\nEu tenho tentado, Senhor, deixe-me lhe dizer,\ndeixe-me lhe dizer, eu realmente fiz o melhor que pude.\nEu tenho trabalhado das sete às onze todas as noites,\neu disse que isto meio que faz da minha vida um saco.\nSenhor, isso não está certo... Não, não.\nDesde que andei amando você,\nestou a ponto de perder minha mente angustiada\nDisse que tenho chorado. Minhas lágrimas parecem chuva,\nVocê não ouve, você não as ouve cair?\nVocê se lembra mulher, quando eu bati em sua porta?\nEu disse que você se atreveu a me falar\nque não me queria mais, é\nEu abro minha porta da frente,\ne escuto minha porta dos fundos bater,\nVocê deve ter um desses amantes mais jovens.\nEu tenho trabalhado das sete, das sete, das sete às onze\ntodas as noites, isto meio que faz da minha vida um saco...\nBaby, desde que andei amando você,\nestou a ponto de perder\nestou a ponto de perder minha mente angustiada\n', 'Português');
            
insert into comentario (texto, avaliacao, fkusuario, fktraducao) 
values		('Tradução ótima', 5, 2, 1),
			('Tem muito o que melhorar', 2, 3, 1),
			('Perfeita, trouxe bem a ideia principal', 5, 4, 1),
            ('Achei que falou alguns pontos', 4, 3, 2),
            ('Bem ruim', 1, 4, 3),
			('Faltou adaptar algumas coisas', 3, 1, 3),
			('Me ajudou muito, adorei', 5, 5, 1),
            ('Muito confusa', 2, 5, 3),
            ('Pode melhorar', 3, 5, 2),
			('Não gostei de alguns pontos', 3, 1, 4),
			('Melhore', 2, 5, 4),
            ('Muito boa', 4, 3, 5),
            ('Finalmente entendi o significado', 5, 2, 5);
            